### ISSUE TITLE
Some questions about protocol responses (enabled events & color data)

### ISSUE THREAD

**Issue by entwanne** [RootRobotics/root-robot-ble-protocol#5] opened 2020-11-06 18:16 UTC
Hi,

I am implementing the root protocol in a library and I'm facing issues with two responses of the robot.

## Command 0.11 - Get Enabled Events Response

I always receive an empty bitfield from this command. The enable/disable event commands work but _Get enabled events_ keeps returning an empty bitfield.

Is this a known issue?

## Command 4.1 - Color Sensor Data Response

With this command, I don't know how to handle the color data I receive, either with ADC or mV format. Is there a way to map the data with RGB colors or is it only brightness data?

Also the protocol says that the result for ADC format is on 12 bits but I get significant bits in the 16 bits of the color data.

Thanks

**Comment by entwanne** [comment] 2021-01-27 12:04
Hello, do you have any information about these commands?

**Comment by shamlian** [comment] 2021-01-29 19:07
Splitting this into two tickets and addressing there. (marking Duplicate of #6 and #7 )

**Closed as completed by shamlian** 2021-01-29 19:07 UTC

**Comment by shamlian** [comment] 2021-01-29 19:09
Also -- @entwanne thank you for reporting these; please join me in the child tickets for updates!
